### PR TITLE
Resolves #141

### LINKED ISSUE #141: duplicate webApplication configuration for loose application
Steps to reproduce the problem

1. `git clone https://github.com/WASdev/sample.servlet.git`
2. update war and liberty configuration in the build.gradle file 
```
//war {
//    archiveName = baseName + '.' + extension
//}

liberty {
    server {
        bootstrapProperties = ['default.http.port': testServerHttpPort,
                               'default.https.port': testServerHttpsPort,
                               'appLocation': "${rootProject.name}-${version}.war",
                               'appContext': warContext]
        name = wlpServerName
        apps = [war]
        stripVersion = false
    }
}
```
3. build the project and check `build/wlp/usr/servers/LibertyProjectServer/configDropins/configDropins/defaults` directory.

I guess the issue is caused by setting `stripVersion=false`

### PR DESCRIPTION
**Pull request by jjvilleg**
resolves #141

### CODE REVIEW

File: src/main/groovy/net/wasdev/wlp/gradle/plugins/utils/ServerConfigDocument.java [hunk 1]
```diff
@@ -367,18 +367,22 @@ private boolean isValidURL(String url) {
...
-                resolved = resolved.replaceAll("\\$\\{" +  varNameMatcher.group(1) + "\\}", variable);
+            String key = varNameMatcher.group(1);
+            String variable = getProperties().getProperty(key);
+            java.util.Iterator it = getProperties().entrySet().iterator();
+            while (it.hasNext()) {
+                Map.Entry pair = (Map.Entry)it.next();
+                if(pair.getKey().equals(key)) {
+                    return pair.getValue().toString();
+                }
+                it.remove(); // avoids a ConcurrentModificationException
```
Comment (cthigh) [inline src/main/groovy/net/wasdev/wlp/gradle/plugins/utils/ServerConfigDocument.java]: this shouldn't be necessary.
