### PR TITLE
fixing facet version issue

### LINKED ISSUE #210: Web facet set to 3.0 but EAR facet set to 5.0
If I import a project that has ear and war sub-projects, for the ear project the EAR facet is set to 5.0 (which is JEE5) and for the war project the Dynamic Web Module facet is set to 3.0 (which is JEE6).  I can't find that it is causing any problems but could the EAR facet be set to 6.0 to be consistent with the web facet?

### PR DESCRIPTION
**Pull request by mattbsox**
Fixes #210 and #211

### CODE REVIEW

File: src/main/groovy/net/wasdev/wlp/gradle/plugins/Liberty.groovy [hunk 1]
```diff
@@ -220,12 +220,11 @@ class Liberty implements Plugin<Project> {
...
-            if(project.plugins.hasPlugin('war')) {
-                setFacetVersion(project, 'jst.web', JST_WEB_FACET_VERSION)
-            } else if(project.plugins.hasPlugin('ear')) {
-                setFacetVersion(project, 'jst.ear', JST_EAR_FACET_VERSION)
-            }
+        if(project.plugins.hasPlugin('war')) {
+            setFacetVersion(project, 'jst.web', JST_WEB_FACET_VERSION)
+        }
+        if(project.plugins.hasPlugin('ear')) {
+            setFacetVersion(project, 'jst.ear', JST_EAR_FACET_VERSION)
```
Comment (cherylking) [inline src/main/groovy/net/wasdev/wlp/gradle/plugins/Liberty.groovy]: This is a nit, but why not move line 227 inside the if at line 230?
