### PR TITLE
Resolved null source set issue. Closes #169

### LINKED ISSUE #169: Could not get unknown property 'sourceSets' ?
I bumped into a strange issue in Win7/64-bit that I do not see on MacOS using this pluging 2.0.1 and Gradle 4.3.1 and Java 8.  I think is is due to this plugin, but I am not sure. Any idea - here is the stacktrace from the build:

```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'sourceSets' for task ':recres-webapp:war' of type org.gradle.api.tasks.bundling.War.
        at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:61)
        at org.gradle.api.tasks.bundling.War_Decorated.getProperty(Unknown Source)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installLooseConfigWar(InstallAppsTask.groovy:156)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installLooseApplication(InstallAppsTask.groovy:139)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installProject(InstallAppsTask.groovy:120)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask$_installMultipleApps_closure1.doCall(InstallAppsTask.groovy:73)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installMultipleApps(InstallAppsTask.groovy:72)
        at net.wasdev.wlp.gradle.plugins.tasks.InstallAppsTask.installApps(InstallAppsTask.groovy:53)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more

```

### PR DESCRIPTION
**Pull request by jjvilleg**

### CODE REVIEW

File: src/main/groovy/net/wasdev/wlp/gradle/plugins/tasks/InstallAppsTask.groovy [hunk 1]
```diff
@@ -152,8 +153,8 @@ class InstallAppsTask extends AbstractServerTask {
     }
 
     protected void installLooseConfigWar(LooseConfigData config, Task task) throws Exception {
-        File dir = getServerDir(project)
-        if (!dir.exists() && !task.sourceSets.allJava.getSrcDirs().isEmpty()) {
+        File outputDir = project.buildDir
+        if (!outputDir.exists() && hasJavaSourceFiles(task.classpath)) {
           throw new GradleException(MessageFormat.format("Failed to install loose application from project {0}. The project has not been compiled.", project.name))
```
Comment (cthigh) [inline src/main/groovy/net/wasdev/wlp/gradle/plugins/tasks/InstallAppsTask.groovy]: were you able to generate this exception?

File: src/main/groovy/net/wasdev/wlp/gradle/plugins/tasks/InstallAppsTask.groovy [hunk 2]
```diff
@@ -168,11 +169,20 @@ class InstallAppsTask extends AbstractServerTask {
         looseWar.addManifestFile(manifestFile, "gradle-war-plugin")
     }
 
+    private boolean hasJavaSourceFiles(FileCollection classpath){
+        for(File f: classpath) {
+            if(f.getAbsolutePath().endsWith('/build/classes/java/main')) {
```
Comment (cthigh) [inline src/main/groovy/net/wasdev/wlp/gradle/plugins/tasks/InstallAppsTask.groovy]: If gradle allows you to configure the source to be someplace other than "java/main", Is is OK to just look for `contains('/build/classes/')`?   Also, I am concerned with this as a hardcoded string. Should we calculate this string from `project.buildDir + "/classes"`.  Better yet, is there a variable for the classes output location?
